/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    HomePlus: typeof import('./src/components/icons/HomePlus.vue')['default']
    HomePlusIcon: typeof import('./src/components/icons/HomePlusIcon.vue')['default']
    ITablerAB2: typeof import('~icons/tabler/a-b2')['default']
    ITablerEye: typeof import('~icons/tabler/eye')['default']
    ITablerEyeOff: typeof import('~icons/tabler/eye-off')['default']
    ITablerHomePlus: typeof import('~icons/tabler/home-plus')['default']
    ITablerLock: typeof import('~icons/tabler/lock')['default']
    ITablerLockCheck: typeof import('~icons/tabler/lock-check')['default']
    ITablerLogin: typeof import('~icons/tabler/login')['default']
    ITablerMail: typeof import('~icons/tabler/mail')['default']
    ITablerMessageCircle: typeof import('~icons/tabler/message-circle')['default']
    ITablerMoon: typeof import('~icons/tabler/moon')['default']
    ITablerSun: typeof import('~icons/tabler/sun')['default']
    ITablerUpload: typeof import('~icons/tabler/upload')['default']
    ITablerUser: typeof import('~icons/tabler/user')['default']
    ITablerUserPlus: typeof import('~icons/tabler/user-plus')['default']
    ITablerUsers: typeof import('~icons/tabler/users')['default']
    ITablerX: typeof import('~icons/tabler/x')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MessageCircle: typeof import('./src/components/icons/MessageCircle.vue')['default']
    MessageCircleIcon: typeof import('./src/components/icons/MessageCircleIcon.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFeatureList: typeof import('./src/components/home/TheFeatureList.vue')['default']
    TheFooter: typeof import('./src/components/home/TheFooter.vue')['default']
    TheHeroSection: typeof import('./src/components/home/TheHeroSection.vue')['default']
    TheNavbar: typeof import('./src/components/layout/TheNavbar.vue')['default']
    Upload: typeof import('./src/components/icons/Upload.vue')['default']
    UploadIcon: typeof import('./src/components/icons/UploadIcon.vue')['default']
    Users: typeof import('./src/components/icons/Users.vue')['default']
    UsersIcon: typeof import('./src/components/icons/UsersIcon.vue')['default']
  }
}
