services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
